config/routes.rb
Rails.application.routes.draw do
  root :to => "pages#home"
  resources :users
  get "/session/characters" => "session#characters"
  get "/session/species" => "session#species"
  get "/session/accessories" => "session#accessories"
  resources :characters
  resources :species
  resources :accessories
  get "/login" => "session#new" # find the session of that browser. unique to each person.
  post "/login" => "session#create"
  delete "/login" => "session#destroy"
  get "/coins" => "session#coins"
  post "/coins/add" => "session#add_coins"
  get "/game" => "pages#game"
  post "/game" => "pages#play"
  post "/game/add" => "pages#add_coins"
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  before_action :check_for_login

  def index
    @species = Species.all
  end

  def new
    @species = Species.new
  end

  def create
    @species = Species.create params_species
    @species.user_id = @current_user.id

    if params[:file].present?
      # Then call Cloudinary's upload method, passing in the file in params
      req = Cloudinary::Uploader.upload(params[:file])
      # need to use URL for the javascript callback when editing dino.
      @species.image = req["url"]
      @species.save
    end

    @current_user.species << @species
    redirect_to species_path(@species)
  end

  def show
    @species = Species.find params[:id]
    # Logic for number of characters using this species
    @num_characters = Character.includes(:species).where('species_id' => @species.id)
  end

  def edit
    # Only show this page, if the character is the @current_user's
    @species = Species.find params[:id]
    if @species.user_id == @current_user.id || @current_user.admin == true
      render :edit
    else
      redirect_to species_path
    end
  end

  def update
    species = Species.find params[:id]

    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      # need to use URL for the javascript callback when editing dino.
      species.image = req["url"]
    end

    species.update params_species
    species.save
    redirect_to species
  end

  def destroy
    Species.destroy params[:id]
    redirect_to species_path
  end

  private
  def params_species
    params.require(:species).permit(:genus, :order, :diet, :image, :fun_fact, :user_id)
  end
end

app/views/species/_form.html.erb
<%= form_for @species, :html => {:multipart => true} do |f| %>
<%= f.label :genus, :autofocus => true, :required => true %>
<%= f.text_field :genus %>

<%= f.label :order, :required => true %>
<%= f.text_field :order %>

<%= f.label :diet, :required => true %>
<%= f.text_field :diet %>

<%= f.label :image, :required => true %>
<%= f.cl_image_upload :image %>

<%= f.label :fun_fact, :required => true %>
<%= f.text_field :fun_fact %>

<%= f.submit %>
<% end %>

app/views/species/edit.html.erb
<div class="loginPage">
  <h1>Edit <%= @species.genus %>!</h1>

  <%= render :partial => 'form' %>
</div>

app/views/species/index.html.erb
<h1>All Species!</h1>

<div class="homeGrid">
<% @species.each do |species| %>
<div>
      <%= link_to image_tag(species.image, :class => "thumb", :id => species.id), species_path(species) %>
    <%= link_to species.genus, species_path(species) %>
  </div>
<% end %>

</div>

app/views/species/new.html.erb
<div class="loginPage">
  <h1>New Species!</h1>

<% if @species.errors.any? %>
<ol>
  <% @species.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ol>
<% end %>


<%= render :partial => 'form' %>
</div>

app/views/species/show.html.erb
<h1><%= @species.genus %>!</h1>

<p>Genus: <%= @species.genus %></p>
<p>Order: <%= @species.order %></p>
<p>Diet: <%= @species.diet %></p>
<% if @species.image.present? %>
      <%= image_tag @species.image, :class => "feature" %>

<% end %>
<p>Fun Fact: <%= @species.fun_fact %></p>
<p>Creator: <%= link_to @species.user.username, user_path(@species.user.id) %></p>

<p>Number of Characters using: <%= @num_characters.count  %></p>

<%# Only allow edit and delete button, if the character is @current_user's %>
<% if @current_user.id == @species.user_id  || @current_user.admin == true%>
  <div class="edit">
    <%= link_to "Edit #{@species.genus}", edit_species_path(@species.id) %>
    <%= button_to "Delete #{@species.genus}!", @species, :method => "delete", :data => {:confirm => "Are you sure?"} %>
  </div>
<% end %>