config/routes.rb
Rails.application.routes.draw do
  root :to => "pages#home"
  resources :users
  get "/session/characters" => "session#characters"
  get "/session/species" => "session#species"
  get "/session/accessories" => "session#accessories"
  resources :characters
  resources :species
  resources :accessories
  get "/login" => "session#new" # find the session of that browser. unique to each person.
  post "/login" => "session#create"
  delete "/login" => "session#destroy"
  get "/coins" => "session#coins"
  post "/coins/add" => "session#add_coins"
  get "/game" => "pages#game"
  post "/game" => "pages#play"
  post "/game/add" => "pages#add_coins"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :text
#  username        :text
#  coins           :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#  admin           :boolean          default(FALSE)
#  profile_image   :text
#  creator         :boolean          default(FALSE)
#

class User < ApplicationRecord
  has_secure_password
  # TODO: check out the rails validates guide to customise
  validates :email, :presence => true, :uniqueness => true

  has_many :accessories
  has_many :characters
  has_many :species
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_login, :only => [:edit, :update]
  before_action :logged_in_send_home, :only => [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if params[:file].present?
      # Then call Cloudinary's upload method, passing in the file in params
      req = Cloudinary::Uploader.upload(params[:file])
      # need to use URL for the javascript callback when editing dino.
      @user.profile_image = req["url"]
      @user.save
    end


    if @user.save
          session[:user_id] = @user.id
          redirect_to root_path
        else
          render :new # do this instead of redirect, so that the form doesnt clear.
        end
  end

  def edit
    if @current_user.admin == true
      @user = User.find params[:id]
    else
      @user = @current_user
    end
  end

  def show
    @user = User.find params[:id]
  end

  def update
    if @current_user.admin == true
      user = User.find params[:id]
    else
      user = @current_user
      # TODO: how to make the coins only pass through if user is an admin.
      params[:coins] = user.coins
    end

    if params[:file].present?
      # Then call Cloudinary's upload method, passing in the file in params
      req = Cloudinary::Uploader.upload(params[:file])
      # need to use URL for the javascript callback when editing dino.
      user.profile_image = req["url"]
      user.save
    end
    user.update user_params
    redirect_to user_path
  end

  def destroy
    user = User.find params[:id]
    if @current_user.admin == true || @current_user.id == user.id
      User.destroy params[:id]
    end
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username, :coins, :profile_image)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="loginPage">
  <h1>Edit User</h1>

  <%= form_for @user, :html => {:multipart => true} do |f| %>
  <%= f.label :email, :autofocus => true, :required => true %>
  <%= f.email_field :email %>

  <%= f.label :username, :required => true %>
  <%= f.text_field :username %>

  <%= f.label :profile_image, :required => true %>
  <%= f.cl_image_upload :profile_image %>

  <% if @user.admin == true %>
    <%= f.label :coins, :required => true %>
    <%= f.number_field :coins %>
  <% end %>

  <%= f.submit %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>All Users!</h1>

<ol>
<% @users.each do |user| %>
  <% if user.admin == false %>
    <li class="index"><%= link_to user.username, user %>
      <% if user.admin == true %>
        <%= image_tag "icon_admin.png", :class => "iconIndex" %>
        <% end %>
      <% if user.creator == true %>
        <%= image_tag "icon_artist.png", :class => "iconIndex" %>
      <% end %>
    </li>
  <% end %>
<% end %>
</ol>

app/views/users/new.html.erb
<div class="loginPage">
  <h1>Sign Up</h1>

  <% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ol>
  <% end %>

  <%= form_for @user, :html => {:multipart => true} do |f| %>

  <%= f.label :username, "Username: *" %>
  <%= f.text_field :username %>

  <%= f.label :profile_image, "Profile Image:" %>
  <%= f.cl_image_upload :profile_image %>

  <%= f.label :email, "E-mail: *" %>
  <%= f.email_field :email %>

  <%= f.label :password, "Password: *" %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password: *" %>
  <%= f.password_field :password_confirmation %><br>

  <%= f.submit "Sign Up!" %>
  <p>or <%= link_to "Sign in", login_path %></p>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="centerContent">
    <h1><% if @user.admin == true %>
          <%= image_tag "icon_admin.png", :class => "iconProfile" %>
        <% end %>
        <% if @user.creator == true %>
          <%= image_tag "icon_artist.png", :class => "iconProfile" %>
        <% end %>
        <%= @user.username %>!</h1>

        <% if @user.profile_image.present? %>
            <%= image_tag @user.profile_image, :class => "profile_image" %>
        <% end %>

    <p class="coin"><%= image_tag "coin.png" %><%= @user.coins  if @user.coins.present?%></p>

    <% if @user.characters.count > 0 %>
    <h2>Characters: </h2>
    <div class="profile_grid">
      <%= render partial: "characters/display_character", collection: @user.characters, as: :character %>
    </div>
    <% end %>


    <%# if they have species, show them here %>
    <% if @user.species.count > 0 %>
    <h2>Species: </h2>
    <div class="profile_grid">
      <% @user.species.each do |species| %>
          <div class="gridContainer"><%= link_to species.genus, species %><br>
              <%= link_to image_tag(species.image, :class => "thumb"), species if species.image.present?  %>

          </div>
      <% end %>
    </div>
    <% end %>

    <% if @user.accessories.count > 0%>
    <h2>Accessories: </h2>
    <div class="profile_grid">
      <% @user.accessories.each do |accessory| %>
          <div class="gridContainer"><%= link_to accessory.name, accessory %><br>
            <%= link_to image_tag(accessory.image, :class => "thumb"), accessory if accessory.image.present?%></div>
      <% end %>
    </div>
    <% end %>



    <%# Only allow edit and delete button, if the user looking is @current_user's %>
    <% if @current_user.id == @user.id || @current_user.admin == true %>
      <div class="edit">
        <%= link_to "Edit #{@user.username}", edit_user_path(@user.id) %>
        <%= button_to "Delete #{@user.username}!", @user, :method => "delete", :data => {:confirm => "Are you sure?"} %>
      </div>
    <% end %>
</div>