config/routes.rb
Rails.application.routes.draw do
  root :to => "pages#home"
  resources :users
  get "/session/characters" => "session#characters"
  get "/session/species" => "session#species"
  get "/session/accessories" => "session#accessories"
  resources :characters
  resources :species
  resources :accessories
  get "/login" => "session#new" # find the session of that browser. unique to each person.
  post "/login" => "session#create"
  delete "/login" => "session#destroy"
  get "/coins" => "session#coins"
  post "/coins/add" => "session#add_coins"
  get "/game" => "pages#game"
  post "/game" => "pages#play"
  post "/game/add" => "pages#add_coins"
end

app/models/character.rb
# == Schema Information
#
# Table name: characters
#
#  id         :bigint           not null, primary key
#  name       :text
#  age        :integer
#  talent     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  species_id :integer
#

class Character < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :species, :optional => true
  has_many :posessions

  def accessory_ids
    self.posessions.map(&:accessory_id)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :text
#  username        :text
#  coins           :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#  admin           :boolean          default(FALSE)
#  profile_image   :text
#  creator         :boolean          default(FALSE)
#

class User < ApplicationRecord
  has_secure_password
  # TODO: check out the rails validates guide to customise
  validates :email, :presence => true, :uniqueness => true

  has_many :accessories
  has_many :characters
  has_many :species
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :check_for_login

  def index
    @characters = Character.all
  end

  def new
    @coins = @current_user.coins
    @character = Character.new
    # Create a hash to link species id with their image, this is added in HTML to be used in main.js
    # TODO: make default image something else - "choose dino" or something.
    @species_images = {}
    @species = Species.all
    @species.each do |s|
      @default_image = s.image if @default_image.nil?
      @species_images[ s.id ] = s.image
    end

    # Create a hash to link accessory id with their image, this is added in HTML to be used in main.js
    @accessory_images = {}
    @accessories = Accessory.all
    @accessories.each do |a|
      @default_image = a.image if @default_image.nil?
      @accessory_images[ a.id ] = a.image
    end
  end

  def create
    # create the character
    @character = Character.create params_character
    @character.user_id = @current_user.id
    @current_user.characters << @character

    # find the checkboxes from params accessory[id][]
    # inside this will be an array of checked accessories.
    # for each of these, create a new Posession
    @posessions = params[:accessory][:id]
    @posessions.each do |p|
      if p.present?
        # TODO: find x and y values for each posession.
        # find the x and y coordinates saved
        @positions = params[:positions]
        @x_pos = 0
        @y_pos = 0

        @positions.each do |key, value|
          if key.include? p
            # they match, find the X and Y values.
            if key.include? "x"
              @x_pos = value
            elsif key.include? "y"
              @y_pos = value
            end
          end
        end

        new_posession = Posession.create :accessory_id => p, :character_id => @character.id, :x_pos => @x_pos, :y_pos => @y_pos
        @character.posessions << new_posession
      end

      # change users coins based on accessories selected.
      @coins = params[:userCoins]
      @current_user.coins = @coins
      @current_user.save
    end

    redirect_to character_path(@character)
  end

  def show
    @character = Character.find params[:id]
    @accessories = Accessory.all
  end

  def edit
    @character = Character.find params[:id]
    @coins = @current_user.coins
    # Create a hash to link species id with their image, this is added in HTML to be used in main.js
    @species_images = {}
    @species = Species.all
    @species.each do |s|
      @default_image = s.image if @default_image.nil?
      @species_images[ s.id ] = s.image
    end

    # Create a hash to link accessory id with their image, this is added in HTML to be used in main.js
    @accessory_images = {}
    @accessories = Accessory.all
    @accessories.each do |a|
      @default_image = a.image if @default_image.nil?
      @accessory_images[ a.id ] = a.image
    end

    # Only show this page, if the character is the @current_user's
    if @character.user_id == @current_user.id || @current_user.admin == true
      render :edit
    else
      redirect_to characters_path
    end
  end

# TODO: how to cause error if dont fill in all required fields
  def update
    character = Character.find params[:id]

    # Before creating a new posession, check if it exists already and if it does just update the X and Y values.

    # find the checkboxes from params accessory[id][]
    # inside this will be an array of checked accessories.
    # for each of these, create a new Posession
    @posessions = params[:accessory][:id]
    @posessions.each do |p|
      if p.present?
        @positions = params[:positions]
        @x_pos = 0
        @y_pos = 0

        @positions.each do |key, value|
          if key.include? p
            # they match, find the X and Y values.
            if key.include? "x"
              @x_pos = value
            elsif key.include? "y"
              @y_pos = value
            end
          end
        end

        # check if posession doesnt already exist.
        if character.posessions.exists?(accessory_id: p)
          # find the posession and remove it from the character
          oldposession = character.posessions.where(accessory_id: p)
          oldposession.each do |item|
            if @x_pos != "30" && @y_pos != "500"
              character.posessions.delete(item)
              # associate a new posession with the updated values.
              new_posession = Posession.create :accessory_id => p, :character_id => character.id, :x_pos => @x_pos, :y_pos => @y_pos
              character.posessions << new_posession
            end
          end
          # if the posession already existed, check if the values have been moved and if they havent then do not remove, nor create a new entry.
        else
          # associate a new posession with the updated values.
          new_posession = Posession.create :accessory_id => p, :character_id => character.id, :x_pos => @x_pos, :y_pos => @y_pos
          character.posessions << new_posession
        end


      end

      # change users coins based on accessories selected.
      @coins = params[:userCoins]
      @current_user.coins = @coins
      @current_user.save
    end

    character.update params_character
    redirect_to character
  end

  def destroy
    Character.destroy params[:id]
    redirect_to characters_path
  end

  private
  def params_character
    params.require(:character).permit(:name, :age, :talent, :user_id, :species_id)
  end

end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_custom_character.html.erb
<div class="character_container">

<div class="accessories_selected" id="accessories_selected">

</div>
  <%= image_tag @default_image, :class => "character_feature", :id => "character_edit" %>
</div>

app/views/characters/_display_character.html.erb
<div>
  <div class="character_container">

    <% if character.species.image.present?  %>
      <% id = "feature_" + character.id.to_s %>

      <% if character.species.image.present? %>
          <%= image_tag character.species.image, :class => "character_feature", :id => id %>
      <% end %>
    <% end %>

    <% if character.posessions.present? %>
      <% character.posessions.each do |p| %>
        <% id = p.accessory_id %>
        <% acc = Accessory.find id %>

        <% if acc.image.include? "." %>
            <%= posession = image_tag acc.image, :class => "character_accessory", :style => "position: absolute; top: #{p.x_pos}%; left: #{p.y_pos}%;" %>
        <% elsif %>
          <%= posession = cl_image_tag acc.image, :class => "character_accessory", :style => "position: absolute; top: #{p.x_pos}%; left: #{p.y_pos}%;" %>
        <% end %>
        <% end %>
      <% end %>

  </div>
    <%= link_to character.name, character_path(character) %>
  </div>

app/views/characters/_form.html.erb
<%= form_for @character do |f| %>
<%= f.label :name, :autofocus => true, :required => true %>
<%= f.text_field :name %>

<%= f.label :age, :required => true %>
<%= f.number_field :age %>

<%= f.label :talent, :required => true %>
<%= f.text_field :talent %>

<%# TODO: add in heading for species dropdown, that is unselectable %>
<%= f.label :species_id, :required => true %>

<%= f.select :species_id, Species.pluck(:genus, :id) %>

<%= f.submit %>
<% end %>

app/views/characters/_form_new.html.erb
<%= form_for @character do |f| %>
<%= f.label :name, :autofocus => true, :required => true %>
<%= f.text_field :name %>

<%= f.label :age, :required => true %>
<%= f.number_field :age %>

<%= f.label :talent, :required => true %>
<%= f.text_field :talent %>

<%# TODO: add in heading for species dropdown, that is unselectable %>
<%= f.label :species_id, :required => true %>

<%# Convert hash from controller that links species id to images into json. %>
<script>
  const speciesImages = <%== @species_images.to_json %>;
</script>

<%= f.select :species_id, Species.pluck(:genus, :id) %>

<script>
  const accessoryImages = <%== @accessory_images.to_json %>;
</script>


<p>Your current coins: <span id="userTempCoins"><%= @coins %></span></p>

  <%= collection_check_boxes(:accessory, :id, Accessory.all, :id, :name) do |b| %>
    <%= b.label(class: "check_box") { b.check_box(class: "check_box", data: "#{b.object.cost}") + b.object.cost.to_s + image_tag(b.object.image, :class => "icon") } %>
 <% end %>


  <% Accessory.all.each do |a| %>
    <%= hidden_field_tag "positions[#{ a.id }_x]", 30 %>
    <%= hidden_field_tag "positions[#{ a.id }_y]", 500 %>
  <% end %>

<%= hidden_field_tag "userCoins", 0 %>
<%= f.submit "Create Dino!" %>
<% end %>

app/views/characters/_show_character.html.erb
<div class="character_container">

  <% if @character.species.image.present?  %>
    <% id = "feature_" + @character.id.to_s %>
    <%= image_tag @character.species.image, :class => "character_feature", :id => id %>
  <% end %>

  <% if @character.posessions.present? %>
    <% @character.posessions.each do |p| %>
      <% id = p.accessory_id %>
      <% acc = Accessory.find id %>
        <%= posession = image_tag acc.image, :class => "character_accessory", :style => "position: absolute; top: #{p.x_pos}%; left: #{p.y_pos}%;" %>
    <% end %>
  <% end %>
</div>

app/views/characters/edit.html.erb
<div class="centerContent editContainer" id="editPage">
  <h1>Edit <%= @character.name %>!</h1>

  <div class="create_character_grid">
    <div class="character_form">
        <%= form_for @character do |f| %>

        <% if @character.errors.any? %>
        <ol>
          <% @character.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ol>
        <% end %>

        <%= f.label :name, :autofocus => true, :required => true %>
        <%= f.text_field :name %>

        <%= f.label :age, :required => true %>
        <%= f.number_field :age %>

        <%= f.label :talent, :required => true %>
        <%= f.text_field :talent %>

        <%# TODO: add in heading for species dropdown, that is unselectable %>
        <%= f.label :species_id, :required => true %>

        <%# Convert hash from controller that links species id to images into json. %>
        <script>
          const speciesImages = <%== @species_images.to_json %>;
        </script>

        <%= f.select :species_id, Species.pluck(:genus, :id) %>
    </div>


    <div class="character_container">
      <div class="accessories_selected" id="accessories_selected">
        <% if @character.posessions.present? %>
          <% @character.posessions.each do |p| %>
            <% id = p.accessory_id %>
            <% acc = Accessory.find id %>
            <%# TODO: give the posession an ID so it is removed when you uncheck. %>
            <% uniqueid = "accessoryRendered" + id.to_s %>
              <%= posession = image_tag acc.image, :class => "character_accessory", :id => uniqueid, :style => "position: absolute; top: #{p.x_pos}%; left: #{p.y_pos}%;" %>
          <% end %>
        <% end %>
      </div>
        <%= image_tag @character.species.image, :class => "character_feature", :id => "character_edit" %>
    </div>


    <script>
      const accessoryImages = <%== @accessory_images.to_json %>;
    </script>

    <div class="character_shop">
        <div class="shopTitle">
          <p class="title">Shop</p>
          <p class="coinCount"><%= image_tag "coin.png" %><span id="userTempCoins"><%= @current_user.coins %></span></p>
        </div>

        <div class="character_shop_grid">
          <%= collection_check_boxes(:accessory, :id, Accessory.all, :id, :name) do |b| %>
            <%= b.label(class: "check_box") { %>
            <%= b.check_box(class: "check_box", data: "#{b.object.cost}", checked: @character.accessory_ids.include?(b.value)) %>
            <div class="accessory_checkbox">
              <span class="accessory_checkbox_cost">
                <%= image_tag "coin.png" %>
                <%= b.object.cost.to_s %>
              </span>
                <%= image_tag(b.object.image, :class => "icon")  %>
            </div>
            <% } %>

          <% end %>


          <% Accessory.all.each do |a| %>
            <%= hidden_field_tag "positions[#{ a.id }_x]", 30 %>
            <%= hidden_field_tag "positions[#{ a.id }_y]", 500 %>
          <% end %>
        </div>
    </div>
    <div class="character_create">
      <%= hidden_field_tag "userCoins", 0 %>
      <%= f.submit "Update Dino!" %>
      <% end %>
    </div>
  </div>
</div>

app/views/characters/index.html.erb
<h1>All DINOS!</h1>
<ol>
<% @characters.each do |character| %>
  <li><%= link_to character.name, character %>, the <%= character.species.genus if character.species.present?  %></li>
<% end %>
</ol>

app/views/characters/new.html.erb
<div class="centerContent">
  <h1>Create a new Dino!</h1>

  <div class="create_character_grid">
    <div class="character_form">
        <%= form_for @character do |f| %>

        <% if @character.errors.any? %>
        <ol>
          <% @character.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ol>
        <% end %>

        <%= f.label :name, :autofocus => true, :required => true %>
        <%= f.text_field :name %>

        <%= f.label :age, :required => true %>
        <%= f.number_field :age %>

        <%= f.label :talent, :required => true %>
        <%= f.text_field :talent %>

        <%# TODO: add in heading for species dropdown, that is unselectable %>
        <%= f.label :species_id, :required => true %>

        <%# Convert hash from controller that links species id to images into json. %>
        <script>
          const speciesImages = <%== @species_images.to_json %>;
        </script>

        <%= f.select :species_id, Species.pluck(:genus, :id) %>
    </div>

      <%= render :partial => 'custom_character' %>

    <script>
      const accessoryImages = <%== @accessory_images.to_json %>;
    </script>

    <div class="character_shop">
        <div class="shopTitle">
          <p class="title">Shop</p>
          <p class="coinCount"><%= image_tag "coin.png" %><span id="userTempCoins"><%= @coins %></span></p>
        </div>

        <div class="character_shop_grid">
          <%= collection_check_boxes(:accessory, :id, Accessory.all, :id, :name) do |b| %>
            <%= b.label(class: "check_box") { %>
            <%= b.check_box(class: "check_box", data: "#{b.object.cost}") %>
            <div class="accessory_checkbox">
              <span class="accessory_checkbox_cost">
                <%= image_tag "coin.png" %>
                <%= b.object.cost.to_s %>
              </span>
                  <%= image_tag(b.object.image, :class => "icon")  %>
            </div>
            <% } %>

          <% end %>


          <% Accessory.all.each do |a| %>
            <%= hidden_field_tag "positions[#{ a.id }_x]", 30 %>
            <%= hidden_field_tag "positions[#{ a.id }_y]", 500 %>
          <% end %>
        </div>
    </div>
    <div class="character_create">
      <%= hidden_field_tag "userCoins", 0 %>
      <%= f.submit "Create Dino!" %>
      <% end %>
    </div>
  </div>
</div>

app/views/characters/show.html.erb
<div class="centerContent">

  <h1><%= @character.name %></h1>
  <div class="characterDisplay">
    <%= render :partial => 'display_character', locals: {character: @character} %>
  </div>

  <div class="characterDescription">
    <p><%= @character.name %> is a <%= @character.species.genus %> from the <%= @character.species.order %> family. They are particularly good at <%= @character.talent %>, especially for the ripe age of <%= @character.age %>.</p>

    <p><%= link_to @character.user.username, user_path(@character.user.id)  %> created this dino.</p>

  </div>

  <%# Only allow edit and delete button, if the character is @current_user's %>
  <% if @current_user.id == @character.user_id || @current_user.admin == true %>
    <div class="edit">
      <%= link_to "Edit #{@character.name}", edit_character_path(@character.id) %>
      <%= button_to "Delete #{@character.name}!", @character, :method => "delete", :data => {:confirm => "Are you sure?"} %>
    </div>
  <% end %>
</div>