config/routes.rb
Rails.application.routes.draw do
  root :to => "pages#home"
  resources :users
  get "/session/characters" => "session#characters"
  get "/session/species" => "session#species"
  get "/session/accessories" => "session#accessories"
  resources :characters
  resources :species
  resources :accessories
  get "/login" => "session#new" # find the session of that browser. unique to each person.
  post "/login" => "session#create"
  delete "/login" => "session#destroy"
  get "/coins" => "session#coins"
  post "/coins/add" => "session#add_coins"
  get "/game" => "pages#game"
  post "/game" => "pages#play"
  post "/game/add" => "pages#add_coins"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dinoland</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= cloudinary_js_config %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="logo navbar-brand">
          <%= link_to "Dinoland", root_path, :class => "logo" %>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="nav navbar-nav ml-auto nav-padding">
            <li class="nav-item"><%= link_to "Home", root_path, :class => "nav-link" %></li>
            <% if @current_user.present? %>
            <li class="nav-item"><%= link_to "Create!", new_character_path, :class => "nav-link" %></li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Boards
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Characters", characters_path, :class => "dropdown-item" %>
                <%= link_to "Species", species_index_path, :class => "dropdown-item" %>
                <%= link_to "Accessories", accessories_path, :class => "dropdown-item" %>
                <%= link_to "All Users", users_path, :class => "dropdown-item" %>
              </div></li>

              <% if @current_user.creator == true || @current_user.admin == true %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Creator
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "Create Species", new_species_path, :class => "dropdown-item" %>
                  <%= link_to "Create Accessory", new_accessory_path, :class => "dropdown-item" %>
                </div></li>
              <% end %>


            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="userName"><%= @current_user.username %></span>
                <%= cl_image_tag @current_user.profile_image, :class => "profileIcon" %>
              </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Account", user_path(@current_user.id), :class => "dropdown-item" %>
              <%= link_to "Add coins", coins_path, :class => "dropdown-item" %>
              <% if @current_user.characters.present? %>
                <%= link_to "Your Characters", session_characters_path, :class => "dropdown-item" %>
              <% end %>
              <% if @current_user.species.present? %>
              <%= link_to "Your Species", session_species_path, :class => "dropdown-item" %>
              <% end %>
              <% if @current_user.accessories.present? %>
              <%= link_to "Your Accessories", session_accessories_path, :class => "dropdown-item" %>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to "logout", login_path, :method => 'delete', :class => "dropdown-item" %>
            </div></li>

            <% else %>
            <li><%= link_to "Sign up", new_user_path, :class => "nav-link" %></li>
            <li><%= link_to "Sign in", login_path, :class => "nav-link" %></li>
            <% end %>
          </ul>
        </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/nav.html.erb
<nav>
  <%= link_to "Home", root_path %> |



  <% if @current_user.present? %>
    <%= link_to "All Users", users_path %> |
    <%= link_to "Add coins", coins_path %>
    <ul>
      <li><%= link_to "Characters", characters_path %></li>
      <li><%= link_to "Your Characters", session_characters_path %></li>
      <li><%= link_to "New Character", new_character_path %></li>
    </ul>
    <ul>
      <li><%= link_to "Species", species_index_path %></li>
      <li><%= link_to "Your Species", session_species_path %></li>
      <li><%= link_to "New Species", new_species_path %></li>
    </ul>
    <ul>
      <li><%= link_to "Accessories", accessories_path %></li>
      <li><%= link_to "Your Accessories", session_accessories_path %></li>
      <li><%= link_to "New Accessory", new_accessory_path %></li>
    </ul>
    <p>Username: <%= link_to @current_user.username, user_path(@current_user.id) %> <br>
      Coins: <%= @current_user.coins %> <br>
    <%= link_to "logout", login_path, :method => 'delete' %>
    </p>

  <% else %>
    <%= link_to "Sign up", new_user_path %>
    <%= link_to "sign in", login_path %>
  <% end %>
</nav>